name: tuukatuu
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.0.1
  share_plus: ^7.2.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_local_notifications: ^15.1.1
  intl: ^0.20.2
  # http: ^0.13.6
  # flutter_polyline_points: ^1.0.0
  google_fonts: ^4.0.4
  # google_maps_webservice: ^0.0.20-nullsafety.5
  # flutter_google_places: ^0.3.0
  flutter_typeahead: ^5.2.0
  # baato_maps: ^1.0.2
  http: ^1.4.0
  flutter_polyline_points: ^3.0.1
  baato_maps: ^1.0.2
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  get_it: ^8.2.0
  carousel_slider: ^5.1.1
  # flutter_native_splash: ^2.4.6
  # url_launcher: ^6.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/products/
    - assets/images/category/
    - assets/images/logo/
    # - assets/icons/
    # - assets/fonts/
    - assets/images/products/coca_cola.jpg
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"


# flutter_native_splash:
#   color: "#ffffff" # background color
#   image: assets/icon/app_icon.png # your splash image
#   android: true
#   ios: true
#   android_gravity: center
#   fullscreen: true

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
