const mongoose = require('mongoose');

const tmartProductSchema = new mongoose.Schema({
  name: { type: String, required: true },
  price: { type: Number, required: true },
  originalPrice: { type: Number },
  imageUrl: { type: String, required: true },
  category: { type: String, required: true },
  subCategory: { type: String },
  brand: { type: String },
  unit: { type: String, default: '1 piece' }, // e.g., '1kg', '500g', '1L'
  weight: { type: Number }, // in grams
  volume: { type: Number }, // in ml
  rating: { type: Number, default: 0 },
  reviews: { type: Number, default: 0 },
  isAvailable: { type: Boolean, default: true },
  stock: { type: Number, default: 0 },
  minOrderQuantity: { type: Number, default: 1 },
  maxOrderQuantity: { type: Number, default: 10 },
  isVegetarian: { type: Boolean, default: false },
  isVegan: { type: Boolean, default: false },
  isGlutenFree: { type: Boolean, default: false },
  isOrganic: { type: Boolean, default: false },
  expiryDate: { type: Date },
  description: { type: String },
  ingredients: [{ type: String }],
  nutritionalInfo: {
    calories: { type: Number },
    protein: { type: Number },
    carbs: { type: Number },
    fat: { type: Number },
    fiber: { type: Number },
  },
  images: [{ type: String }],
  dealTag: { type: String }, // e.g., 'Buy 1 Get 1', '₹99 Store'
  dealExpiresAt: { type: Date },
  discount: { type: Number, default: 0 }, // percentage
  isFeatured: { type: Boolean, default: false },
  isBestSeller: { type: Boolean, default: false },
  isNewArrival: { type: Boolean, default: false },
  tags: [{ type: String }], // for search and filtering
  vendorId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  categoryId: { type: mongoose.Schema.Types.ObjectId, ref: 'TMartCategory' },
}, { timestamps: true });

// Add indexes for better performance
tmartProductSchema.index({ category: 1, isAvailable: 1 });
tmartProductSchema.index({ isFeatured: 1, isAvailable: 1 });
tmartProductSchema.index({ isBestSeller: 1, isAvailable: 1 });
tmartProductSchema.index({ tags: 1 });
tmartProductSchema.index({ name: 'text', description: 'text' });

// Virtual for discount percentage
tmartProductSchema.virtual('discountPercentage').get(function() {
  if (this.originalPrice && this.price) {
    return Math.round(((this.originalPrice - this.price) / this.originalPrice) * 100);
  }
  return 0;
});

// Static method for seeding T-Mart products
tmartProductSchema.statics.seedTMartProducts = async function() {
  const products = [
    // Fruits & Vegetables
    {
      name: 'Fresh Bananas',
      price: 40.0,
      originalPrice: 50.0,
      imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=400&fit=crop',
      category: 'Fruits & Vegetables',
      subCategory: 'Fruits',
      brand: 'Organic Valley',
      unit: '1kg',
      weight: 1000,
      rating: 4.6,
      reviews: 156,
      stock: 40,
      isVegetarian: true,
      isVegan: true,
      isOrganic: true,
      description: 'Sweet and ripe bananas',
      ingredients: ['Bananas'],
      nutritionalInfo: {
        calories: 89,
        protein: 1.1,
        carbs: 23,
        fat: 0.3,
        fiber: 2.6,
      },
      dealTag: '20% OFF',
      discount: 20,
      isFeatured: true,
      tags: ['bananas', 'fruits', 'organic', 'sweet'],
    },
    {
      name: 'Fresh Tomatoes',
      price: 30.0,
      originalPrice: 40.0,
      imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
      category: 'Fruits & Vegetables',
      subCategory: 'Vegetables',
      brand: 'Farm Fresh',
      unit: '1kg',
      weight: 1000,
      rating: 4.2,
      reviews: 89,
      stock: 25,
      isVegetarian: true,
      isVegan: true,
      description: 'Fresh red tomatoes',
      ingredients: ['Tomatoes'],
      nutritionalInfo: {
        calories: 18,
        protein: 0.9,
        carbs: 3.9,
        fat: 0.2,
        fiber: 1.2,
      },
      dealTag: '25% OFF',
      discount: 25,
      tags: ['tomatoes', 'vegetables', 'fresh'],
    },
    {
      name: 'Fresh Apples',
      price: 120.0,
      originalPrice: 150.0,
      imageUrl: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&h=400&fit=crop',
      category: 'Fruits & Vegetables',
      subCategory: 'Fruits',
      brand: 'Apple Valley',
      unit: '1kg',
      weight: 1000,
      rating: 4.4,
      reviews: 134,
      stock: 30,
      isVegetarian: true,
      isVegan: true,
      description: 'Crisp and juicy apples',
      ingredients: ['Apples'],
      nutritionalInfo: {
        calories: 52,
        protein: 0.3,
        carbs: 14,
        fat: 0.2,
        fiber: 2.4,
      },
      dealTag: '20% OFF',
      discount: 20,
      tags: ['apples', 'fruits', 'fresh'],
    },
    {
      name: 'Fresh Broccoli',
      price: 80.0,
      originalPrice: 100.0,
      imageUrl: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400&h=400&fit=crop',
      category: 'Fruits & Vegetables',
      subCategory: 'Vegetables',
      brand: 'Green Valley',
      unit: '1kg',
      weight: 1000,
      rating: 4.1,
      reviews: 67,
      stock: 20,
      isVegetarian: true,
      isVegan: true,
      description: 'Fresh green broccoli',
      ingredients: ['Broccoli'],
      nutritionalInfo: {
        calories: 34,
        protein: 2.8,
        carbs: 7,
        fat: 0.4,
        fiber: 2.6,
      },
      dealTag: '20% OFF',
      discount: 20,
      tags: ['broccoli', 'vegetables', 'green'],
    },

    // Dairy & Eggs
    {
      name: 'Fresh Milk',
      price: 45.0,
      originalPrice: 50.0,
      imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop',
      category: 'Dairy & Eggs',
      subCategory: 'Milk',
      brand: 'Amul',
      unit: '1L',
      weight: 1000,
      rating: 4.5,
      reviews: 120,
      stock: 50,
      isVegetarian: true,
      isOrganic: false,
      description: 'Fresh, pure cow milk',
      ingredients: ['Milk'],
      nutritionalInfo: {
        calories: 42,
        protein: 3.4,
        carbs: 5.0,
        fat: 1.0,
        fiber: 0,
      },
      dealTag: '10% OFF',
      discount: 10,
      isFeatured: true,
      tags: ['milk', 'dairy', 'fresh', 'organic'],
    },
    {
      name: 'Farm Fresh Eggs',
      price: 60.0,
      originalPrice: 70.0,
      imageUrl: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&h=400&fit=crop',
      category: 'Dairy & Eggs',
      subCategory: 'Eggs',
      brand: 'Farm Fresh',
      unit: '12 pcs',
      weight: 600,
      rating: 4.3,
      reviews: 89,
      stock: 30,
      isVegetarian: false,
      isOrganic: true,
      description: 'Farm fresh organic eggs',
      ingredients: ['Eggs'],
      nutritionalInfo: {
        calories: 155,
        protein: 13,
        carbs: 1.1,
        fat: 11,
        fiber: 0,
      },
      dealTag: '14% OFF',
      discount: 14,
      isBestSeller: true,
      tags: ['eggs', 'organic', 'farm fresh'],
    },
    {
      name: 'Cheddar Cheese',
      price: 200.0,
      originalPrice: 250.0,
      imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=400&fit=crop',
      category: 'Dairy & Eggs',
      subCategory: 'Cheese',
      brand: 'Britannia',
      unit: '200g',
      weight: 200,
      rating: 4.4,
      reviews: 78,
      stock: 25,
      isVegetarian: true,
      description: 'Aged cheddar cheese',
      ingredients: ['Milk', 'Salt', 'Enzymes'],
      nutritionalInfo: {
        calories: 402,
        protein: 25,
        carbs: 1.3,
        fat: 33,
        fiber: 0,
      },
      dealTag: '20% OFF',
      discount: 20,
      tags: ['cheese', 'cheddar', 'dairy'],
    },
    {
      name: 'Greek Yogurt',
      price: 60.0,
      originalPrice: 75.0,
      imageUrl: 'https://images.unsplash.com/photo-1547514701-42782101795e?w=400&h=400&fit=crop',
      category: 'Dairy & Eggs',
      subCategory: 'Yogurt',
      brand: 'Danone',
      unit: '150g',
      weight: 150,
      rating: 4.6,
      reviews: 92,
      stock: 35,
      isVegetarian: true,
      description: 'Creamy Greek yogurt',
      ingredients: ['Milk', 'Live Cultures'],
      nutritionalInfo: {
        calories: 59,
        protein: 10,
        carbs: 3.6,
        fat: 0.4,
        fiber: 0,
      },
      dealTag: '20% OFF',
      discount: 20,
      tags: ['yogurt', 'greek', 'dairy'],
    },

    // Bakery
    {
      name: 'Whole Wheat Bread',
      price: 35.0,
      originalPrice: 40.0,
      imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop',
      category: 'Bakery',
      subCategory: 'Bread',
      brand: 'Britannia',
      unit: '400g',
      weight: 400,
      rating: 4.2,
      reviews: 67,
      stock: 25,
      isVegetarian: true,
      isVegan: true,
      isGlutenFree: false,
      description: 'Healthy whole wheat bread',
      ingredients: ['Whole wheat flour', 'Water', 'Yeast', 'Salt'],
      nutritionalInfo: {
        calories: 265,
        protein: 9,
        carbs: 49,
        fat: 3.2,
        fiber: 7,
      },
      dealTag: '12% OFF',
      discount: 12,
      tags: ['bread', 'whole wheat', 'healthy'],
    },
    {
      name: 'Chocolate Cake',
      price: 250.0,
      originalPrice: 300.0,
      imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=400&fit=crop',
      category: 'Bakery',
      subCategory: 'Cakes',
      brand: 'Bakery Fresh',
      unit: '500g',
      weight: 500,
      rating: 4.7,
      reviews: 45,
      stock: 15,
      isVegetarian: true,
      description: 'Delicious chocolate cake',
      ingredients: ['Flour', 'Sugar', 'Cocoa', 'Eggs', 'Milk'],
      nutritionalInfo: {
        calories: 371,
        protein: 5.4,
        carbs: 58,
        fat: 14,
        fiber: 2.1,
      },
      dealTag: '17% OFF',
      discount: 17,
      isFeatured: true,
      tags: ['cake', 'chocolate', 'bakery'],
    },

    // Meat & Fish
    {
      name: 'Atlantic Salmon',
      price: 800.0,
      originalPrice: 1000.0,
      imageUrl: 'https://images.unsplash.com/photo-1516594798947-e65505dbb29d?w=400&h=400&fit=crop',
      category: 'Meat & Fish',
      subCategory: 'Fish',
      brand: 'Ocean Fresh',
      unit: '500g',
      weight: 500,
      rating: 4.5,
      reviews: 34,
      stock: 10,
      isVegetarian: false,
      description: 'Fresh Atlantic salmon fillet',
      ingredients: ['Salmon'],
      nutritionalInfo: {
        calories: 208,
        protein: 25,
        carbs: 0,
        fat: 12,
        fiber: 0,
      },
      dealTag: '20% OFF',
      discount: 20,
      tags: ['salmon', 'fish', 'fresh'],
    },
    {
      name: 'Fresh Chicken Breast',
      price: 300.0,
      originalPrice: 350.0,
      imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop',
      category: 'Meat & Fish',
      subCategory: 'Chicken',
      brand: 'Farm Fresh',
      unit: '1kg',
      weight: 1000,
      rating: 4.3,
      reviews: 56,
      stock: 20,
      isVegetarian: false,
      description: 'Fresh chicken breast',
      ingredients: ['Chicken'],
      nutritionalInfo: {
        calories: 165,
        protein: 31,
        carbs: 0,
        fat: 3.6,
        fiber: 0,
      },
      dealTag: '14% OFF',
      discount: 14,
      tags: ['chicken', 'breast', 'meat'],
    },

    // Snacks
    {
      name: 'Potato Chips',
      price: 50.0,
      originalPrice: 60.0,
      imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&h=400&fit=crop',
      category: 'Snacks',
      subCategory: 'Chips',
      brand: 'Lay\'s',
      unit: '100g',
      weight: 100,
      rating: 4.1,
      reviews: 123,
      stock: 40,
      isVegetarian: true,
      description: 'Crispy potato chips',
      ingredients: ['Potatoes', 'Oil', 'Salt'],
      nutritionalInfo: {
        calories: 536,
        protein: 7,
        carbs: 53,
        fat: 35,
        fiber: 4.4,
      },
      dealTag: '17% OFF',
      discount: 17,
      tags: ['chips', 'potato', 'snacks'],
    },
    {
      name: 'Mixed Nuts',
      price: 150.0,
      originalPrice: 180.0,
      imageUrl: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400&h=400&fit=crop',
      category: 'Snacks',
      subCategory: 'Nuts',
      brand: 'Nature\'s Basket',
      unit: '200g',
      weight: 200,
      rating: 4.6,
      reviews: 89,
      stock: 30,
      isVegetarian: true,
      isVegan: true,
      description: 'Premium mixed nuts',
      ingredients: ['Almonds', 'Cashews', 'Walnuts', 'Pistachios'],
      nutritionalInfo: {
        calories: 607,
        protein: 20,
        carbs: 22,
        fat: 54,
        fiber: 7,
      },
      dealTag: '17% OFF',
      discount: 17,
      isBestSeller: true,
      tags: ['nuts', 'mixed', 'healthy'],
    },

    // Beverages
    {
      name: 'Orange Juice',
      price: 120.0,
      originalPrice: 150.0,
      imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=400&fit=crop',
      category: 'Beverages',
      subCategory: 'Juices',
      brand: 'Tropicana',
      unit: '1L',
      volume: 1000,
      rating: 4.4,
      reviews: 98,
      stock: 35,
      isVegetarian: true,
      isVegan: true,
      description: '100% pure orange juice',
      ingredients: ['Orange juice'],
      nutritionalInfo: {
        calories: 45,
        protein: 0.7,
        carbs: 10.4,
        fat: 0.2,
        fiber: 0.2,
      },
      dealTag: '20% OFF',
      discount: 20,
      isBestSeller: true,
      tags: ['orange juice', 'beverages', 'fresh'],
    },
    {
      name: 'Green Tea',
      price: 80.0,
      originalPrice: 100.0,
      imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop',
      category: 'Beverages',
      subCategory: 'Tea',
      brand: 'Lipton',
      unit: '100 bags',
      weight: 100,
      rating: 4.2,
      reviews: 67,
      stock: 25,
      isVegetarian: true,
      isVegan: true,
      description: 'Natural green tea',
      ingredients: ['Green tea leaves'],
      nutritionalInfo: {
        calories: 1,
        protein: 0,
        carbs: 0.2,
        fat: 0,
        fiber: 0,
      },
      dealTag: '20% OFF',
      discount: 20,
      tags: ['tea', 'green', 'beverages'],
    },

    // Household
    {
      name: 'Laundry Detergent',
      price: 200.0,
      originalPrice: 250.0,
      imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop',
      category: 'Household',
      subCategory: 'Cleaning',
      brand: 'Surf Excel',
      unit: '1kg',
      weight: 1000,
      rating: 4.0,
      reviews: 45,
      stock: 20,
      description: 'Powerful laundry detergent',
      ingredients: ['Surfactants', 'Enzymes', 'Fragrance'],
      dealTag: '20% OFF',
      discount: 20,
      tags: ['detergent', 'laundry', 'cleaning'],
    },

    // Personal Care
    {
      name: 'Shampoo',
      price: 150.0,
      originalPrice: 180.0,
      imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop',
      category: 'Personal Care',
      subCategory: 'Hair Care',
      brand: 'Head & Shoulders',
      unit: '400ml',
      volume: 400,
      rating: 4.3,
      reviews: 78,
      stock: 30,
      description: 'Anti-dandruff shampoo',
      ingredients: ['Water', 'Sodium Laureth Sulfate', 'Zinc Pyrithione'],
      dealTag: '17% OFF',
      discount: 17,
      tags: ['shampoo', 'hair care', 'personal care'],
    },

    // Wine & Beer
    {
      name: 'Jam Shed Red Blend',
      price: 1200.0,
      originalPrice: 1500.0,
      imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=400&fit=crop',
      category: 'Wine & Beer',
      subCategory: 'Red Wine',
      brand: 'Jam Shed',
      unit: '750ml',
      volume: 750,
      rating: 4.5,
      reviews: 89,
      stock: 25,
      isVegetarian: true,
      isVegan: true,
      description: 'Premium red blend wine with rich flavors',
      ingredients: ['Red grapes', 'Alcohol'],
      nutritionalInfo: {
        calories: 85,
        protein: 0,
        carbs: 2.6,
        fat: 0,
        fiber: 0,
      },
      dealTag: '20% OFF',
      discount: 20,
      isFeatured: true,
      tags: ['wine', 'red wine', 'jam shed', 'premium'],
    },
    {
      name: 'White Wine Chardonnay',
      price: 1100.0,
      originalPrice: 1400.0,
      imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=400&fit=crop',
      category: 'Wine & Beer',
      subCategory: 'White Wine',
      brand: 'Vineyard Select',
      unit: '750ml',
      volume: 750,
      rating: 4.3,
      reviews: 67,
      stock: 20,
      isVegetarian: true,
      isVegan: true,
      description: 'Crisp and refreshing chardonnay',
      ingredients: ['White grapes', 'Alcohol'],
      nutritionalInfo: {
        calories: 82,
        protein: 0,
        carbs: 2.4,
        fat: 0,
        fiber: 0,
      },
      dealTag: '21% OFF',
      discount: 21,
      tags: ['wine', 'white wine', 'chardonnay', 'crisp'],
    },
    {
      name: 'Craft Beer IPA',
      price: 350.0,
      originalPrice: 450.0,
      imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=400&fit=crop',
      category: 'Wine & Beer',
      subCategory: 'Beer',
      brand: 'Local Brewery',
      unit: '650ml',
      volume: 650,
      rating: 4.6,
      reviews: 123,
      stock: 40,
      isVegetarian: true,
      isVegan: true,
      description: 'Hoppy India Pale Ale with citrus notes',
      ingredients: ['Malt', 'Hops', 'Yeast', 'Water'],
      nutritionalInfo: {
        calories: 150,
        protein: 1.5,
        carbs: 12,
        fat: 0,
        fiber: 0,
      },
      dealTag: '22% OFF',
      discount: 22,
      isBestSeller: true,
      tags: ['beer', 'ipa', 'craft beer', 'hoppy'],
    },
    {
      name: 'Premium Whiskey',
      price: 2500.0,
      originalPrice: 3000.0,
      imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=400&fit=crop',
      category: 'Wine & Beer',
      subCategory: 'Spirits',
      brand: 'Highland Reserve',
      unit: '750ml',
      volume: 750,
      rating: 4.7,
      reviews: 156,
      stock: 15,
      isVegetarian: true,
      isVegan: true,
      description: 'Smooth and aged premium whiskey',
      ingredients: ['Barley', 'Water', 'Yeast'],
      nutritionalInfo: {
        calories: 250,
        protein: 0,
        carbs: 0,
        fat: 0,
        fiber: 0,
      },
      dealTag: '17% OFF',
      discount: 17,
      isFeatured: true,
      tags: ['whiskey', 'premium', 'aged', 'smooth'],
    },
  ];

  await this.deleteMany({});
  await this.insertMany(products);
};

module.exports = mongoose.model('TMartProduct', tmartProductSchema); 